# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=1000)),
                ('op2', models.CharField(max_length=1000)),
                ('op3', models.CharField(max_length=1000)),
                ('op4', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Junior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('logintime', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.IntegerField(default=1800)),
                ('array', models.CharField(blank=True, max_length=1000, null=True)),
                ('ans_array', models.CharField(blank=True, max_length=1000, null=True)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('logintime', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.IntegerField(default=1800)),
                ('array', models.CharField(blank=True, max_length=1000, null=True)),
                ('ans_array', models.CharField(blank=True, max_length=1000, null=True)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='squestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=1000)),
                ('op2', models.CharField(max_length=1000)),
                ('op3', models.CharField(max_length=1000)),
                ('op4', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=5)),
            ],
        ),
    ]
