# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junior',
            name='logintime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='senior',
            name='logintime',
            field=models.IntegerField(default=0),
        ),
    ]
