# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round1', '0003_auto_20160316_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='percent_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senior',
            name='percent_flag',
            field=models.IntegerField(default=0),
        ),
    ]
