# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round1', '0004_auto_20160316_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junior',
            name='college',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='junior',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='junior',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='junior',
            name='user1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='junior',
            name='user2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='senior',
            name='college',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='senior',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='senior',
            name='user1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='senior',
            name='user2',
            field=models.CharField(max_length=15),
        ),
    ]
