# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round1', '0005_auto_20160317_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junior',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
